# Generated by Django 2.0rc1 on 2017-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_auto_20171203_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Выбор продуктов для главной',
                'verbose_name_plural': 'Выбор продуктов для главной',
            },
        ),
    ]
